resources/views/livewire/cache.blade.php
resources/views/livewire/queues.blade.php
resources/views/livewire/slow-outgoing-requests.blade.php

Hello,
On a fresh install, going to `/pulse` results in the following error: https://flareapp.io/share/87nK4ry5
Adding missing use for `Illuminate\Support\Str` in 3 blade views fixed the issue.

Fix Class "Str" not found error on fresh install

---

database/migrations/2023_06_07_000001_create_pulse_tables.php

Correction of the error that occurs during migration.
` SQLSTATE[HY000]: General error: 1478 Table storage engine 'MyISAM' does not support the create option 'Index on virtual generated column' (Connection: mysql, SQL: alter table pulse_values add unique pulse_values_type_key_hash_unique(type, key_hash))`
This PR close #103

Switching engine to InnoDB

---

src/Entry.php

Small amendment to the DocComment so it accurately reflects what the method does.

[1.x] Fix `isOnlyBuckets` DocComment

---

src/PulseServiceProvider.php

The route registration is currently delayed until the app has `booted`.
This causes catch-all routes to take precedence.
If an app has the following route:
```php
Route::get('{foo}', function () {
return view('welcome');
});
```
Pulse will not be accessible. This PR fixes that by registering the routes as soon as the router is resolved.

[1.x] Ensure catch-all routes do not take precedence

---

src/Livewire/Concerns/RemembersQueries.php

While creating custom cards you might want to be able to set a longer cache duration without having to create a custom trait.

[1.x] Add possibility to change cache duration

---

src/Recorders/Exceptions.php
src/Recorders/SlowQueries.php

I have windows operating system, it was showing wrong path in both the files.
I replaced the '/' with the `DIRECTORY_SEPARATOR` constant to ensure consistent directory separation across different operating systems.
before
after
in Exception

[1.x] Fix file path in SlowQueries.php AND Exceptions.php

---

src/Support/RedisAdapter.php

Fixes:
- Predis raw command arguments on v2.
- Ensures server exception messages always has a "message".
- PHPStan linting.

[1.x] Redis adapter improvements

---

UPGRADE.MD
database/migrations/2023_06_07_000001_create_pulse_tables.php
tests/Pest.php

We don't need these, but it seems some DB providers do, such as PlanetScale and DigitalOcean managed DBs.
Fixes https://github.com/laravel/pulse/issues/136, https://github.com/laravel/pulse/issues/108

[1.x] Support DB configurations that _require_ a unique ID

---

src/Pulse.php
src/PulseServiceProvider.php

Similiar to other first pary packages i thought it would be great to allow ignoring route registration, in order to be able to register the routes yourself. A more practical use case might be if you use something like tenancy for laravel where registring the routes only on central domains, etc.. can be beneficial and easir to be created that way

[1.x] Allow ignoring route registration

---

src/Facades/Pulse.php
src/Pulse.php
src/PulseServiceProvider.php
tests/TestCase.php

Similiar to other first pary packages i thought it would be great to allow publishing migrations. Same as in this pr #80: a more practical use case might be if you use something like tenancy for laravel where you might want to have those migrations for your tenant databases as well

[1.x] Make migrations publishable

---

src/PulseServiceProvider.php

We provide sensible default middleware for most applications, but we have hardcoded the `web` middleware as a fallback when there isn't any.
If a user has change their configuration I think we should respect it.
Additionally, not all applications will have a `web` middleware defined, so we can't rely on it as a safe fallback.
Fixes https://github.com/laravel/pulse/issues/146

[1.x] Remove default `web` middleware

---

resources/views/components/pulse.blade.php
src/Facades/Pulse.php
src/Livewire/Card.php
src/Pulse.php
tests/Feature/Livewire/CustomCardTest.php
tests/fixtures/custom.css

This PR introduces a way for custom cards to load any CSS they need.
The challenge:
* Blade stacks won't work for "lazy" cards unless the CSS is pushed from the placeholder view rather than the render view.
* Any `<link>` tags directly in the card would require packages to publish CSS to the application's `public` directory, and lazy-loaded cards would have a _flash of unstyled content_ when the card is loaded.
* If a package contains multiple cards sharing a single CSS file, the CSS should only be included on the page once, regardless of how many cards are used.
* If a package contains multiple cards with dedicated CSS files, only the CSS for the cards that are being used should be included on the page.
The solution:
Custom cards can now implement a `css` method when extending the `Card` …

[1.x] Custom card CSS

---

resources/views/livewire/cache.blade.php
tests/Feature/Livewire/CacheTest.php

Due to how we are handing rounding, we can sometimes show a `100%` hit rate for cache keys, even when there are misses.
This PR removes the use of `round` and just uses `int` casting to trim the decimal without performing any rounding. We maintain 2 decimal places.

[1.x] Fix number rounding on cache card

---

src/Livewire/Cache.php

Fixes a deprecation notice and also just creates an expected value.
Fixes https://github.com/laravel/pulse/issues/166

[1.x] Ensure values always contain an integer

---

config/pulse.php
resources/views/livewire/slow-queries.blade.php
src/Livewire/SlowQueries.php

Some SQL queries being captured are rather long, as seen in https://github.com/laravel/pulse/issues/167 where the query overflows the TEXT column.
We've also seen some performance issues in the browser, likely due to syntax highlighting: https://github.com/laravel/pulse/issues/160
This adds a flag to disable syntax highlighting of SQL queries on the fly.

[1.x] Add the ability to disable SQL highlighting

---

src/Contracts/Storage.php
src/Entry.php
src/Storage/DatabaseStorage.php
tests/Feature/Storage/DatabaseStorageTest.php

This PR adds support for "sum" and "min" aggregations, in addition to the "max", "avg", and "count" aggregations we already support.
Also refactored some of the logic to not loop over the entries more than needed, and abstracted the repeated preaggregation logic now that we have five methods.
Cc @aarondfrancis

[1.x] Add "sum" and "min" aggregations

---

src/PulseServiceProvider.php

Currently, if you "disable" Pulse it acts as if you never installed it.
- No events are registered
- The dashboard is not accessible
- The commands are not accessible
- The pulse class is not registered as a singleton
etc.
This might seem like a good idea, but i think it is more problematic.
Imagine you are running Pulse and you are having troubles. You decide to "disable" pulse and redeploy your application.
If you had `php artisan pulse:restart` in your deploy script, you deployment just broke because we don't register that command any more.
I think that the enabled switch should really only impact the recorders. We already document that this is what the flag does.
One question I do have, though, is if the `pulse:work` command and `pulse:check` command should first look to see if pulse …

[1.x] Improve enabled flag

---

resources/views/livewire/usage.blade.php

Before | After
:-------------------------:|:-------------------------:

[1.x] Fix avatar size

---

UPGRADE.MD

I was checking the upgrade guide to see what will need actioning when 1.x is released and noticed the first link under required pointed to the wrong PR.

Amend link in upgrade guide

---

src/Recorders/CacheInteractions.php

It's _technically_ possible to use a `null` key with `Cache::put` and `Cache::get`. This PR fixes an error in Pulse when this is the case by converting it to an empty string.
Fixes #215

Handle `null` cache keys

---

UPGRADE.MD
config/pulse.php
src/Ingests/RedisIngest.php
src/Livewire/SlowQueries.php
src/Pulse.php
tests/Feature/RedisTest.php

If the `pulse:work` command fails the Ingest will continue to build up in size.
With Redis this is problematic as it is keeping itself in memory. When the `pulse:work` command fails we already trim the ingest on a lottery whenever we put data into the ingest, but it will always retain 7 days worth of data.
That could be problematic for some application depending on their traffic size.
This PR allows the maximum retention for the ingest to be configured.
This value is respected whenever the ingest is trimmed, so it is not guaranteed that the ingest will only contain the configured value until trimming occurs, which again, may happen on a lottery basis.
You may specifiy either a time period or a number of entries to retain.
```php
// ...
'ingest' => [
'trim' => [
// Keep an interval... …
```

[1.x] Allow configurable trim length

---

src/Pulse.php
tests/Feature/Livewire/CustomCardTest.php

This PR fixes an issue where a `Htmlable` object could not be returned from the `css` method if it did not contain a `__toString` method.

[1.x] Fix passing of `Htmlable` class without `__toString` method

---

config/pulse.php

While in local development with a low threshold. I ended up with lots of telescope entries in the slow queries table. This made the dashboard very slow with over 1000 slow queries.

[1.x] Ignore telescope for slow queries by default

---

src/Commands/ClearCommand.php
src/PulseServiceProvider.php
tests/Feature/Commands/ClearCommandTest.php

Renamed PurgeCommand to ClearCommand to align with the naming convention used in the Telescope package.
This pull request addresses the need for consistency in command naming across packages. The existing command, PurgeCommand, has been renamed to ClearCommand to harmonize with the conventions established in the Telescope package.
Maintaining a consistent naming scheme is crucial for code readability and collaboration. Aligning the command names with those in the Telescope package not only improves uniformity within across the codebases but also enhances the overall developer experience.

Renamed purge to clear

---

database/migrations/2023_06_07_000001_create_pulse_tables.php
src/Support/PulseMigration.php

Database migrations are ignored ✅
---
Throws an exception pointing developer to disable pulse if they want to.
---
Throws an exception indicating that the DB is not supported.
---
Throws an exception indicating that the DB is not supported. This is important because we don't want to record in the migrations table that the migration has been run, because enabling pulse later will not work.

[1.x] Improve migration errors to guide developers with unsupported drivers

---

src/Recorders/Servers.php
tests/Feature/Recorders/ServersTest.php

This PR updates the servers recorder to work with the output from the `top` command on Alpine Linux (i.e. the BusyBox version) in addition to the "procps-ng" version currently supported.
For reference, the `top` output looks like this with BusyBox:
```sh
Mem: 9138956K used, 1041152K free, 808552K shrd, 419480K buff, 4727092K cached
CPU:  12% usr   2% sys   0% nic  82% idle   0% io   0% irq   0% sirq
Load average: 0.56 0.50 0.47 1/813 116610
```
And this with procps-ng:
```sh
top - 16:18:24 up 2 days,  3:43,  2 users,  load average: 0.90, 1.05, 1.87
Tasks: 586 total,   2 running, 579 sleeping,   0 stopped,   5 zombie
%Cpu(s):  2.1 us,  4.3 sy,  0.0 ni, 93.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  31737.7 total,   2068.5 free,  17295.9 used,  14860.7 buff/cache
MiB Swap:   8192.0 …
```

[1.x] Support BusyBox/Alpine `top` output

---

src/Commands/CheckCommand.php
src/Commands/ClearCommand.php
src/Commands/WorkCommand.php
src/Contracts/Ingest.php
src/Facades/Pulse.php
src/Ingests/RedisIngest.php
src/Ingests/StorageIngest.php
src/Pulse.php
src/PulseServiceProvider.php
tests/Feature/Commands/ClearCommandTest.php
tests/Feature/Ingests/DatabaseTest.php
tests/Feature/Livewire/CacheTest.php
tests/Feature/Livewire/ExceptionsTest.php
tests/Feature/Livewire/QueuesTest.php
tests/Feature/Livewire/ServersTest.php
tests/Feature/Livewire/SlowJobsTest.php
tests/Feature/Livewire/SlowOutgoingRequestsTest.php
tests/Feature/Livewire/SlowQueriesTest.php
tests/Feature/Livewire/SlowRequestsTest.php
tests/Feature/Livewire/UsageTest.php
tests/Feature/PulseTest.php
tests/Feature/Recorders/CacheInteractionsTest.php
tests/Feature/Recorders/ExceptionsTest.php
tests/Feature/Recorders/QueuesTest.php
tests/Feature/Recorders/SlowJobsTest.php
tests/Feature/Recorders/SlowOutgoingRequestsTest.php
tests/Feature/Recorders/SlowQueriesTest.php
tests/Feature/RedisTest.php
tests/Feature/Storage/DatabaseStorageTest.php
tests/Pest.php

This PR addresses memory leaks where Pulse's internal activity creates new entries that are never persisted. It also addresses memory leaks present in the `pulse:work` command.

[1.x] Ignore all internal pulse activity

---

src/Ingests/NullIngest.php
src/PulseServiceProvider.php

Because Pulse is active in production, it is also good to have it enabled in your testsuite.
This introduces a "null" driver that may be used in testsuites to keep the logic parts of Pulse active, but have the persistence side of things ignored to improve performance of your local testsuite.

[1.x] Null ingest

---

src/Contracts/Storage.php
src/Storage/DatabaseStorage.php
tests/Feature/Storage/DatabaseStorageTest.php

This PR improves the return value of the `aggregateTotal` method when only a single type is requested.
```php
$total = Pulse::aggregateTotal('cache_hit', 'count');
```
```
// Before
Illuminate\Support\Collection {
#items: array:1 [
"cache_hit" => "12.00"
]
}
// After
12.0
```
The current return type is maintained when passing the first parameter as an array of types.

[1.x] Make `aggregateTotal` return a float when a single type is requested

---

src/Contracts/ResolvesUsers.php
src/LegacyUsers.php
src/Livewire/Usage.php
src/Users.php
tests/Feature/PulseTest.php

This PR makes a minor tweak to the unreleased changes in #251, based on what felt better when writing the docs.
It renames the `fields` method to `find` and returns an object instead of an array because objects feel nicer to work with in Blade views.
**Before**
```php
$users = Pulse::resolveUsers($aggregates->pluck('key'));
$aggregates->map(fn ($aggregate) => (object) [
'user' => (object) $users->fields($aggregate->key),
// ...
]);
```
**After**
```php
$users = Pulse::resolveUsers($aggregates->pluck('key'));
$aggregates->map(fn ($aggregate) => (object) [
'user' => $users->find($aggregate->key),
// ...
]);
```

[1.x] Rename `fields` method and return an object

---

src/Livewire/Card.php

This fixes an issue with the return type on the `aggregateTotal` helper based on the changes in #259.

[1.x] Fix helper return

---

src/Commands/CheckCommand.php

This PR fixes an issue when using the file cache driver where the cache locks would continue growing on disk. This is due to the file cache driver not automatically removing files when the cache item has expired.
Fixes #238

[1.x] Prevent `pulse:check` from filling the file cache

---

src/Users.php

This way it is not nessessary to change `find()` method for custom user resolver.

Use (potentially overloaded) key() method for finding user
